<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>RccBoq.RestMcp</AssemblyName>
    <RootNamespace>RccBoq.RestMcp</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RccBoq.RestCore\RccBoq.RestCore.csproj" />
  </ItemGroup>
</Project>
